Feature/feeds
Vestanra/vacancy-browse pull request #2
Opened 2024-10-30 10:58 UTC by Vestanra

feeds table with styles

2024-10-31 14:19 UTC, Vestanra commented
Added routes, sidebar, and layout.

2024-11-01 18:45 UTC, Vestanra commented
Created Feed By ID page

2024-11-04 07:39 UTC, AndriiKasian requested changes

2024-11-04 07:39 UTC, AndriiKasian commented on src/components/helpers/styles/overflow.css
> +.css-qr46ko::-webkit-scrollbar {
- [ ] what kind of class name is this?

2024-11-04 08:21 UTC, AndriiKasian approved these changes

2024-11-04 08:24 UTC, merged