Feature/chats
Vestanra/vacancy-browse pull request #3
Opened 2024-11-07 08:41 UTC by Vestanra

2024-11-11 09:46 UTC, AndriiKasian requested changes

2024-11-11 09:46 UTC, AndriiKasian commented on src/services/socket.ts
> +
- [ ] use import { Manager } from 'socket.io-client'; to create socketManager

2024-11-11 09:46 UTC, AndriiKasian commented on src/components/Chats/ChaItem.tsx
> +        const socket: Socket = io(socketUrl, {
- [ ] this part of socket should be in the socket manager

2024-11-11 09:46 UTC, AndriiKasian commented on src/components/Chats/ChaItem.tsx
> +        socket.on(NotificationEvents.ChatResponse, () => {
- [ ] on NotificationEvents.ChatResponse you just need to add response message to the chat list, but not refetch

2024-11-11 09:46 UTC, AndriiKasian commented on src/components/Chats/ChaItem.tsx
> +        socket.on('connect', () => handleConnect(socket, requestBody));
- [ ] move all logic related to the socket functionality to the custom hook

2024-11-11 19:21 UTC, Vestanra commented
add socket manager, update chat message logic, add custom hooks for socket and data fetching

2024-11-28 07:49 UTC, AndriiKasian approved these changes

2024-11-28 10:57 UTC, merged